# Generated by Django 6.0.2 on 2026-02-07 21:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=60)),
                ('file_url', models.URLField()),
                ('duration_seconds', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('uploaded', 'uploaded'), ('processing', 'processing'), ('ready', 'ready'), ('failed', 'failed')], default='uploaded')),
                ('short_requested', models.CharField(max_length=50)),
                ('width', models.IntegerField()),
                ('height', models.IntegerField()),
                ('aspect_ratio', models.IntegerField()),
                ('file_size', models.PositiveIntegerField()),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
