# Generated by Django 6.0.2 on 2026-03-01 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='has_audio',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
