# Generated by Django 6.0.2 on 2026-03-02 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='type_short',
            field=models.CharField(blank=True, choices=[('vertical', 'Vertical'), ('horizontal', 'Horizontal')], max_length=20, null=True),
        ),
    ]
