# Generated by Django 6.0.2 on 2026-02-09 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Processing_Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_type', models.CharField(choices=[('shorts_generation', 'shorts_generation'), ('cover_generation', 'cover_generation')], default='shorts_generation')),
                ('status', models.CharField(choices=[('pending', 'pending'), ('running', 'running'), ('completed', 'completed'), ('failed', 'failed')], default='pending')),
                ('progress', models.FloatField()),
                ('started_at', models.DateTimeField()),
                ('finished_at', models.DateTimeField()),
                ('attempt_count', models.PositiveIntegerField()),
                ('error_message', models.CharField(max_length=200)),
                ('create_at', models.DateTimeField()),
            ],
        ),
        migrations.AlterField(
            model_name='video',
            name='aspect_ratio',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='video',
            name='short_requested',
            field=models.PositiveIntegerField(),
        ),
    ]
