# Generated by Django 6.0.2 on 2026-02-12 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processingjob',
            name='job_type',
            field=models.CharField(choices=[('shorts_generation', 'shorts_generation')], default='shorts_generation', max_length=50),
        ),
        migrations.AlterField(
            model_name='video',
            name='duration_seconds',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
