# Generated by Django 6.0.2 on 2026-02-09 13:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0002_processing_job_alter_video_aspect_ratio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='processing_job',
            name='video',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='Video', to='videos.video'),
            preserve_default=False,
        ),
    ]
