# Generated by Django 6.0.2 on 2026-03-04 01:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0002_video_has_audio'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='type_short',
            field=models.CharField(choices=[('vertical', 'Vertical'), ('horizontal', 'Horizontal')], db_index=True, default='vertical', max_length=20),
        ),
        migrations.AddIndex(
            model_name='video',
            index=models.Index(fields=['user', 'type_short'], name='videos_vide_user_id_bf804a_idx'),
        ),
    ]
