# Generated by Django 6.0.2 on 2026-02-12 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Short',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_url', models.URLField(max_length=500)),
                ('cloudinary_public_id', models.CharField(max_length=255)),
                ('start_second', models.PositiveIntegerField()),
                ('end_second', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('generating', 'generating'), ('ready', 'ready'), ('failed', 'failed')], default='generating', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cover_url', models.URLField(blank=True, max_length=500, null=True)),
            ],
        ),
    ]
