# Generated by Django 6.0.2 on 2026-02-07 21:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('videos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Short',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_url', models.URLField()),
                ('start_second', models.PositiveIntegerField()),
                ('end_second', models.PositiveIntegerField()),
                ('height', models.IntegerField()),
                ('width', models.IntegerField()),
                ('status', models.CharField(choices=[('generating', 'generating'), ('ready', 'ready'), ('failed', 'failed')], default='generating')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='short', to='videos.video')),
            ],
        ),
    ]
