# Generated by Django 6.0.2 on 2026-02-09 13:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shorts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cover',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.URLField()),
                ('frame_second', models.PositiveIntegerField()),
                ('is_selected', models.BooleanField()),
                ('short', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='short', to='shorts.short')),
            ],
        ),
    ]
