# Generated by Django 6.0.2 on 2026-02-16 02:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shorts', '0001_initial'),
        ('videos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='short',
            name='video',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shorts', to='videos.video'),
        ),
        migrations.AddIndex(
            model_name='short',
            index=models.Index(fields=['video', 'created_at'], name='shorts_shor_video_i_16a05b_idx'),
        ),
        migrations.AddIndex(
            model_name='short',
            index=models.Index(fields=['status'], name='shorts_shor_status_57eecc_idx'),
        ),
    ]
