# Generated by Django 6.0.2 on 2026-02-17 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shorts', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='short',
            name='end_second',
            field=models.DecimalField(decimal_places=3, max_digits=8),
        ),
        migrations.AlterField(
            model_name='short',
            name='start_second',
            field=models.DecimalField(decimal_places=3, max_digits=8),
        ),
    ]
