# Generated by Django 6.0.2 on 2026-02-14 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shorts', '0002_initial'),
        ('videos', '0004_alter_processingjob_options_alter_video_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='short',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='short',
            name='cover_cloudinary_public_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='short',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='short',
            name='status',
            field=models.CharField(choices=[('generating', 'Generating'), ('ready', 'Ready'), ('failed', 'Failed')], db_index=True, default='generating', max_length=20),
        ),
        migrations.AddIndex(
            model_name='short',
            index=models.Index(fields=['video', 'created_at'], name='shorts_shor_video_i_16a05b_idx'),
        ),
        migrations.AddIndex(
            model_name='short',
            index=models.Index(fields=['status'], name='shorts_shor_status_57eecc_idx'),
        ),
    ]
