export const MOCK_PROJECTS = [
    {
        id: '1',
        file_name: 'Tech Review - iPhone 15',
        create_at: '2 hours ago',
        status: 'ready',
        file_url: 'https://picsum.photos/seed/tech/200/300',
        duration_seconds: 120,
        short_requested: 3,
        width: 1920,
        height: 1080,
        aspect_ratio: '16:9',
        file_size: 15728640 // 15MB
    },
    {
        id: '2',
        file_name: 'Gym Vlog #42',
        create_at: 'Yesterday',
        status: 'ready',
        file_url: 'https://picsum.photos/seed/gym/200/300',
        duration_seconds: 300,
        short_requested: 5,
        width: 3840,
        height: 2160,
        aspect_ratio: '16:9',
        file_size: 104857600 // 100MB
    },
    {
        id: '3',
        file_name: 'Cooking Pasta',
        create_at: '3 days ago',
        status: 'failed',
        file_url: 'https://picsum.photos/seed/food/200/300',
        duration_seconds: 45,
        short_requested: 1,
        width: 1080,
        height: 1920,
        aspect_ratio: '9:16',
        file_size: 5242880 // 5MB
    },
    {
        id: '4',
        file_name: 'Travel Vlog: Japan',
        create_at: '1 week ago',
        status: 'processing',
        file_url: 'https://picsum.photos/seed/japan/200/300',
        duration_seconds: 600,
        short_requested: 10,
        width: 1920,
        height: 1080,
        aspect_ratio: '16:9',
        file_size: 209715200 // 200MB
    },
    {
        id: '5',
        file_name: 'Coding Tutorial',
        create_at: '2 weeks ago',
        status: 'ready',
        file_url: 'https://picsum.photos/seed/code/200/300',
        duration_seconds: 1200,
        short_requested: 2,
        width: 2560,
        height: 1440,
        aspect_ratio: '16:9',
        file_size: 419430400 // 400MB
    },
    {
        id: '6',
        file_name: 'Cat Compilation',
        create_at: '1 month ago',
        status: 'ready',
        file_url: 'https://picsum.photos/seed/cat/200/300',
        duration_seconds: 60,
        short_requested: 4,
        width: 1280,
        height: 720,
        aspect_ratio: '16:9',
        file_size: 8388608 // 8MB
    },
];
